src/co/twibble/spring/model/Twibble.java
/**
 * 
 */
package co.twibble.spring.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
 
import co.twibble.spring.model.TwibbleUser;

/**
 * Entity bean with JPA annotations
 * Hibernate provides JPA implementation
 * @author Andy McCall
 *
 */
@Entity
@Table(name="TWIBBLES")
public class Twibble {

	@Id
    @Column(name="TWIBBLEID")
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private int twibbleId;
    
	@Column(name = "TEXT", nullable = false)
    private String text;

    @ManyToOne
    @JoinColumn(name ="USERID")
	private TwibbleUser user;
	
    public int getTwibbleId() {
        return this.twibbleId;
    }
 
    public void setId(int twibbleid) {
        this.twibbleId = twibbleid;
    }
 
    public String getText() {
        return this.text;
    }
 
    public void setText(String text) {
        text = this.text;
    }  

   public String getUsername() {
      return this.user.getUsername();
   }
   
   public String getFullName() {
	   return this.user.getFullName();
   }
    
   @Override
   public String toString(){
       return "twibbleId= "+ getTwibbleId() + ", text= " + getText() + ", username= " + getUsername();
   }
	
}

src/co/twibble/spring/model/TwibbleUser.java
/**
 * 
 */
package co.twibble.spring.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
 
/**
 * Entity bean with JPA annotations
 * Hibernate provides JPA implementation
 * @author Andy McCall
 *
 */
@Entity
@Table(name="Users")
public class TwibbleUser {

	@Id
    @Column(name="USERID")
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private int userId;

	@Column(name = "USERNAME", nullable = false)
	private String username;
	
	@Column(name = "FIRSTNAME", nullable = false)
	private String firstName;
	
	@Column(name = "LASTNAME", nullable = false)
	private String lastName;

	@Column(name = "EMAILADDRESS", nullable = false)
	private String emailAddress;
	
	public int getUserId() {
        return userId;
    }
 
    public void setUserId(int userId) {
        this.userId = userId;
    }
	
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username ;
    }
    
    public void setFirstName(String firstname) {
         this.firstName = firstname ;
    }
    
    public String getFirstName() {
        return this.firstName;
    }
   
    public void setLastName(String lastname) {
        this.lastName = lastname ;
   }
   
   public String getLastName() {
       return this.lastName;
   }
    
   public String getFullName() {   
	   return this.firstName + " " + this.lastName;
   }
   
    public String getEmailAddress() {
    	return emailAddress;
    }

    public void setEmailAddress(String emailaddress) {
    	this.emailAddress = emailaddress;
    }

	@Override
    public String toString(){
        return "userId=" + userId + "," + "username=" + username + "," + "firstName:" + firstName + "," + "lastName:" + lastName;
    }
	
}

src/co/twibble/spring/TwibbleController.java
/**
 * 
 */
package co.twibble.spring;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.MessageSource;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import co.twibble.spring.model.Twibble;
import co.twibble.spring.model.TwibbleUser;
import co.twibble.spring.service.TwibbleService;
import co.twibble.spring.service.TwibbleUserService;
 
/**
 * @author Andy McCall
 *
 */
@Controller
public class TwibbleController {

	@Autowired
    TwibbleService twibbleService;

	@Autowired
	TwibbleUserService twibbleUserService;
     
    @Autowired
    MessageSource messageSource;
 
    /*
     * This method will list all existing twibbles.
     */
    @RequestMapping(value = { "/", "/twibbles" }, method = RequestMethod.GET)
    public String listTwibbles(Model model) {
 
        List<Twibble> twibbles = twibbleService.listTwibbles();
        model.addAttribute("twibbles", twibbles);
        return "twibbles";
    }
  
    /*
     * This method will list all existing users.
     */
    
    @RequestMapping(value = { "/users" }, method = RequestMethod.GET)
    public String listUsers(Model model) {
 
        List<TwibbleUser> users = twibbleUserService.listUsers();
        model.addAttribute("users", users);
        return "users";
    }
    
 // show add user form
 	@RequestMapping(value = "/users/add", method = RequestMethod.GET)
 	public String showAddUserForm(Model model) {

 		TwibbleUser user = new TwibbleUser();

 		// set default value
 		user.setUsername("Username");
 		user.setFirstName("First Name");
 		user.setLastName("Last Name");
 		user.setEmailAddress("first.last@address.com");
 		model.addAttribute("userForm", user);

 		return "userform";

 	}

 	@RequestMapping(value = "/users", method = RequestMethod.POST)
	public String saveOrUpdateUser(@ModelAttribute("userForm") TwibbleUser user,
			BindingResult result, Model model, 
			final RedirectAttributes redirectAttributes) {
 		
			twibbleUserService.addUser(user);
			return "redirect:/users";

		}
 	
 	@RequestMapping(value = "/users/{userId}/", method = RequestMethod.GET)
 	public String showUserForm(Model model, @PathVariable("userId") int userId) {

 		TwibbleUser user = twibbleUserService.getUserById(userId);

 		model.addAttribute("user", user);

 		return "user";

 	}
    
    @RequestMapping(value = "/users/{userId}/delete", method = RequestMethod.POST)
	public String deleteUser(@PathVariable("userId") int userId, 
		final RedirectAttributes redirectAttributes) {

		twibbleUserService.deleteUserById(userId);
		return "redirect:/users";

	}

}

WebContent/views/fragments/footer.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<div class="container">
	<hr>
	<footer>
		<p>&copy; Twibble.co 2015</p>
	</footer>
</div>

<spring:url value="/resources/scripts/bootstrap.min.js"	var="bootstrapJs" />
<spring:url value="/resources/scripts/jquery-2.1.4.min.js" var="jqueryJs" />

<script src="${jqueryJs}"></script>
<script src="${bootstrapJs}"></script>



WebContent/views/fragments/header.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>

<head>
<title>Twibble</title>

<spring:url value="/resources/css/bootstrap.min.css" var="bootstrapCss" />

<link href="${bootstrapCss}" rel="stylesheet" />

</head>

<spring:url value="/" var="urlHome" />
<spring:url value="/users/add" var="urlAddUser" />

<nav class="navbar navbar-inverse ">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="${urlHome}">Twibble</a>
		</div>
		<div id="navbar">
			<ul class="nav navbar-nav navbar-right">
				<li class="active"><a href="${urlAddUser}">Add User</a></li>
			</ul>
		</div>
	</div>
</nav>

WebContent/views/twibbles.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>

	<jsp:include page="/views/fragments/header.jsp" />

    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <title>Twibble</title>
 
</head>
 
<body>
    <h2>List of Twibbles</h2>  
 
 <div class="row">
  <div class="col-sm-4"></div>
  
  <div class="col-sm-4">
   <table>
        <c:forEach items="${twibbles}" var="twibble">
        <div class="container">
            <tr>
            	<td><b>${twibble.fullName}</b>, @${twibble.username}</td>
            </tr>
            <tr>
            	<td>${twibble.text}</td>
            </tr>
        </div>
        <br/>
        </c:forEach>
    </table>
  
  </div>
  
  <div class="col-sm-4"></div>
</div>
 
    <jsp:include page="/views/fragments/footer.jsp" />
    
</body>
</html>

WebContent/views/user.jsp
<%@ page session="false"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<!DOCTYPE html>
<html lang="en">

    <jsp:include page="/views/fragments/header.jsp" />

<div class="container">

	<h1>User Detail</h1>
	<br />

	<div class="row">
		<label class="col-sm-2">UserID</label>
		<div class="col-sm-10">${user.userId}</div>
	</div>

	<div class="row">
		<label class="col-sm-2">Username</label>
		<div class="col-sm-10">${user.username}</div>
	</div>

	<div class="row">
		<label class="col-sm-2">First Name</label>
		<div class="col-sm-10">${user.firstName}</div>
	</div>

	<div class="row">
		<label class="col-sm-2">Last Name</label>
		<div class="col-sm-10">${user.lastName}</div>
	</div>

	<div class="row">
		<label class="col-sm-2">Email</label>
		<div class="col-sm-10">${user.emailAddress}</div>
	</div>

</div>

       <jsp:include page="/views/fragments/footer.jsp" />

</body>
</html>

WebContent/views/userform.jsp
<%@ page session="false"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<!DOCTYPE html>
<html lang="en">

    <jsp:include page="/views/fragments/header.jsp" />

<div class="container">

	<h1>Add User</h1>
	
	<br />

	<spring:url value="/users" var="userActionUrl" />

	<form:form class="form-horizontal" method="post" 
                modelAttribute="userForm" action="${userActionUrl}">

		<form:hidden path="userId" />

		<spring:bind path="username">
		  <div class="form-group ${status.error ? 'has-error' : ''}">
			<label class="col-sm-2 control-label">Username</label>
			<div class="col-sm-10">
				<form:input path="username" type="text" class="form-control" 
                                id="username" placeholder="username" />
				<form:errors path="username" class="control-label" />
			</div>
		  </div>
		</spring:bind>

		<spring:bind path="firstName">
		  <div class="form-group ${status.error ? 'has-error' : ''}">
			<label class="col-sm-2 control-label">First Name</label>
			<div class="col-sm-10">
				<form:input path="firstName" type="text" class="form-control" 
                                id="firstName" placeholder="firstName" />
				<form:errors path="firstName" class="control-label" />
			</div>
		  </div>
		</spring:bind>

		<spring:bind path="lastName">
		  <div class="form-group ${status.error ? 'has-error' : ''}">
			<label class="col-sm-2 control-label">First Name</label>
			<div class="col-sm-10">
				<form:input path="lastName" type="text" class="form-control" 
                                id="lastName" placeholder="lastName" />
				<form:errors path="lastName" class="control-label" />
			</div>
		  </div>
		</spring:bind>

		<spring:bind path="emailAddress">
		  <div class="form-group ${status.error ? 'has-error' : ''}">
			<label class="col-sm-2 control-label">Email</label>
			<div class="col-sm-10">
				<form:input path="emailAddress" class="form-control" 
                                id="emailAddress" placeholder="emailAddress" />
				<form:errors path="emailAddress" class="control-label" />
			</div>
		  </div>
		</spring:bind>

		<div class="form-group">
		  <div class="col-sm-offset-2 col-sm-10">
			     <button type="submit" class="btn btn-primary pull-right">Add</button>
		  </div>
		</div>
	</form:form>

</div>

       <jsp:include page="/views/fragments/footer.jsp" />

</body>
</html>

WebContent/views/users.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<html>
<head>

    <jsp:include page="/views/fragments/header.jsp" />

    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <title>Twibble Users</title>
 
</head>
 
<body>

    <div class="container">
    <h2>Twibble Users</h2>  
    <p id="demo"></p>
    <table class="table table-striped">
    <thead>
      <tr>
        <th>UserID</th>
        <th>Username</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email Address</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
        <c:forEach items="${users}" var="users">
            <tr>
              <spring:url value="/users/${users.userId}/" var="userUrl" />
              <td><a href="${userUrl}">${users.userId}</a></td>
              <td>${users.username}</td>
              <td>${users.firstName}</td>
              <td>${users.lastName}</td>
              <td>${users.emailAddress}</td>
              <td><button type="button" class="btn btn-warning">Modify</button></td>
              
              <td>
              <spring:url value="/users/${users.userId}/delete" var="deleteUrl" />             
              <button type="button" class="btn btn-danger" onclick="this.disabled=true;post('${deleteUrl}')">Delete</button></td>
            </tr>
        </c:forEach>
      </tbody>
    </table>
</div>   
    
       <jsp:include page="/views/fragments/footer.jsp" />
 
  <script>
function post(path, params, method) {
	method = method || "post"; 

	var form = document.createElement("form");
	form.setAttribute("method", method);
	form.setAttribute("action", path);
	
	document.body.appendChild(form);
	form.submit();
	
}

</script>
  
</body>
</html>